import {
  BadRequestException,
  Injectable,
  NotFoundException,
} from '@nestjs/common';
import { randomInt } from 'crypto';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { JwtService } from '@nestjs/jwt';
import { GoogleLoginDto } from './dto/google-login.dto';
import { SendOtpDto } from './dto/send-otp.dto';
import { VerifyOtpDto } from './dto/verify-otp.dto';
import { PhoneVerification, Role, User } from '../entities';
import { RoleName } from '../common/enums/role-name.enum';

@Injectable()
export class AuthService {
  constructor(
    @InjectRepository(User)
    private readonly usersRepository: Repository<User>,
    @InjectRepository(Role)
    private readonly rolesRepository: Repository<Role>,
    @InjectRepository(PhoneVerification)
    private readonly phoneVerificationRepository: Repository<PhoneVerification>,
    private readonly jwtService: JwtService,
  ) {}

  async googleLogin(dto: GoogleLoginDto) {
    const customerRole = await this.ensureRole(RoleName.CUSTOMER);
    const normalizedEmail = dto.email.toLowerCase();
    let user = await this.usersRepository.findOne({
      where: [
        { email: normalizedEmail },
        ...(dto.googleId ? [{ googleId: dto.googleId }] : []),
      ],
    });

    if (!user) {
      user = this.usersRepository.create({
        email: normalizedEmail,
        fullName: dto.fullName,
        googleId: dto.googleId ?? null,
        roleId: customerRole.id,
        phoneVerified: false,
      });
    } else {
      user.fullName = dto.fullName;
      user.googleId = dto.googleId ?? user.googleId;
    }

    const savedUser = await this.usersRepository.save(user);
    const token = await this.jwtService.signAsync({
      sub: savedUser.id,
      role: savedUser.role?.name ?? customerRole.name,
      email: savedUser.email,
    });

    return {
      accessToken: token,
      user: {
        id: savedUser.id,
        fullName: savedUser.fullName,
        email: savedUser.email,
        role: savedUser.role?.name ?? customerRole.name,
        phone: savedUser.phone,
        phoneVerified: savedUser.phoneVerified,
      },
      requiresPhoneVerification: !savedUser.phoneVerified,
      googleVerificationTodo:
        'TODO: Verify Google idToken using Google OAuth endpoint for production.',
    };
  }

  async sendOtp(dto: SendOtpDto) {
    const user = await this.usersRepository.findOne({
      where: { id: dto.userId },
    });
    if (!user) {
      throw new NotFoundException('User not found.');
    }

    const otpCode = `${randomInt(100000, 999999 + 1)}`;
    const verification = this.phoneVerificationRepository.create({
      userId: user.id,
      phone: dto.phone,
      otpCode,
      expiresAt: new Date(Date.now() + 5 * 60 * 1000),
      verified: false,
    });

    await this.phoneVerificationRepository.save(verification);

    return {
      verificationId: verification.id,
      otpProvider: 'mock',
      message: 'OTP generated by mock provider.',
      devOtpCode: otpCode,
      todo: 'TODO: Integrate real SMS OTP provider in production.',
    };
  }

  async verifyOtp(dto: VerifyOtpDto) {
    const verification = await this.phoneVerificationRepository.findOne({
      where: {
        userId: dto.userId,
        phone: dto.phone,
        verified: false,
      },
      order: { createdAt: 'DESC' },
    });

    if (!verification) {
      throw new NotFoundException('No pending OTP verification found.');
    }

    if (verification.expiresAt.getTime() < Date.now()) {
      throw new BadRequestException('OTP code expired.');
    }

    if (verification.otpCode !== dto.otpCode) {
      throw new BadRequestException('Invalid OTP code.');
    }

    verification.verified = true;
    await this.phoneVerificationRepository.save(verification);
    await this.usersRepository.update(
      { id: dto.userId },
      { phone: dto.phone, phoneVerified: true },
    );

    return { success: true, message: 'Phone verification completed.' };
  }

  private async ensureRole(roleName: RoleName): Promise<Role> {
    const role = await this.rolesRepository.findOne({
      where: { name: roleName },
    });
    if (role) {
      return role;
    }

    return this.rolesRepository.save(
      this.rolesRepository.create({ name: roleName }),
    );
  }
}
